name: "🌎 Add Site"
description: Add a new site to the BlogScroll index
type: Feature
labels:
- enhancement
- needs-triage
body:
- type: markdown
  attributes:
    value: Please make sure to [read the FAQ](https://github.com/blogscroll/blogscroll#-faq) before submitting the request. If the content of this issue is already covered in the FAQ, it will be closed.

 - type: checkboxes
    id: terms
    attributes:
      label: FAQ acknowledgement
      description: I read and agree to follow the rules outlined in [the BlogScroll FAQ](https://github.com/blogscroll/blogscroll#-faq). 
      options:
        - label: I read the FAQ
          required: true

- type: input
  attributes:
    label: Site name
    placeholder: Your site name
    description: Enter your readable site name as it will be displayed on BlogScroll.
  validations:
    required: true

- type: input
  attributes:
    label: Site URL
    placeholder: https://blogscroll.com
    description: Enter your site URL.
  validations:
    required: true

- type: input
  attributes:
    label: Favicon URL
    placeholder: https://blogscroll.com
    description: Enter the URL to the icon used for the site, as it will be displayed on BlogScroll. Ensure that icon can be accessed across domains.
  validations:
    required: true

- type: dropdown
  attributes:
    label: Site category
    description: Which category does your site belong to?
    multiple: false
    options:
      - design-and-ux
      - personal
      - photo-video-production
      - technology
      - Other (please specify in "Additional Notes")
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional notes
    description: Add any other relevant context.
    placeholder: My site is awesome. 
  validations:
    required: true
