name: Approve Issue

on:
  issue_comment:
    types: [created]

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - name: Check comment author and content
        id: check_comment
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');

            const comment = github.context.payload.comment;
            const issue = github.context.payload.issue;

            if (comment?.user?.login === 'dend' && comment?.body?.trim() === '/approved') {
              core.setOutput('approved', 'true');
              core.setOutput('issue_number', issue.number);
            } else {
              core.setOutput('approved', 'false');
            }

      - name: Remove 'needs-triage' label and add 'approved'
        if: steps.check_comment.outputs.approved == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = parseInt(steps.check_comment.outputs.issue_number, 10);

            await github.rest.issues.removeLabel({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: issueNumber,
              name: 'needs-triage'
            });

            await github.rest.issues.addLabels({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: issueNumber,
              labels: ['approved']
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
