baseURL = "http://example.org/"
languageCode = "en-us"
title = "BlogScroll - Personal Blog & Site Directory"
theme = "directory"

[params]
description = "This is an open directory of personal sites and blogs, maintained entirely on GitHub."