baseURL = "https://blogscroll.com/"
languageCode = "en-us"
title = "BlogScroll - Personal Blog & Site Directory"
theme = "directory"

[params]
description = "An open directory of personal sites and blogs, maintained entirely on GitHub."